midtermMaulana/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('post/', include('post.urls'))
]

post/urls.py
from django.urls import path
from . import views

app_name = 'post'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:post_id>/', views.detail, name ='detail'),
    path('<int:post_id>/update', views.update, name='update'),
    path('create/', views.create, name='create')
]

post/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    date_created = models.DateTimeField('date created')
    date_updated = models.DateTimeField('date updated')
    content = models.TextField(max_length=1000)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return 'Posts: {}'. format(self.title)

class Comment(models.Model):

    date_created = models.DateTimeField('date created')
    content = models.TextField(max_length=1000)
    post = models.ForeignKey(Post, # Foreign Key from the Question class
                on_delete=models.CASCADE,
                related_name='comments')

post/forms.py
from django.forms import ModelForm
from .models import Post


class PostModelForm(ModelForm):
    class Meta:
        model = Post
        exclude = ['id']

class PostForm(ModelForm):
    class Meta:
        model = Post
        exclude = ['id']

post/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Post
from .forms import PostModelForm
from .forms import PostForm

# Create your views here.

def index(request):
    context = {}
    posts = Post.objects.all()
    context['posts'] = posts
    return render(request, 'index.html', context)


def detail(request, post_id):
    context = {}
    post['post'] = Post.objects.get(id=question_id)
    return render(request, 'detail.html', context)

def update(request, post_id):
    context = {}
    post = Post.objects.get(id=question_id)
    if request.method == 'POST':
        form = PostModelForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return HttpResponse('Post Updated')
        else:
            context['form'] = form
            render(request, 'update.html', context)
    else:
        context['form'] = PostModelForm(instance=post)
        return render(request, 'update.html', context)

def create(request):

    context = {}
    form = PostForm()

    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse('Post Created')

    return render(request, 'create.html', {'form': form})

post/templates/base.html
<html>
  <head>
    <title>
      {% block head %}
        this is the title page
      {% endblock %}
    </title>


  </head>
  <body>
    {% block body %}

    {% endblock %}
  </body>


</html>

post/templates/create.html
{% extends 'base.html' %}
{% block head %}
  this is the update page
{% endblock %}

{% block body %}
<form action="{% url 'post:create' %}" method="POST">
  {% csrf_token %}
  {% for field in form %}
    {{ field.errors }}
    {{ field.label }} {{ field }} <br/>
  {% endfor %}
  <input type="submit" value="Create">
</form>
{% endblock %}

post/templates/detail.html
{% extends 'base.html' %}
{% block head %}
  this is the detail page
{% endblock %}

{% block body %}

  {{post.title}} <br/>
  {{post.date_created}}
  {% for choice in question.choice.all %}
            {{choice.choice_text}} | votes: {{choice.votes}}

  {% endfor %}
{% endblock %}

post/templates/index.html
{% extends 'base.html' %}
{% block head %}
  this is the index page
{% endblock %}
<ol>
{% block body %}
  {% for post in posts %}
    <li>
      <a href="{% url 'post:detail' post.id %}"> Post: {{post.title}} <br />
    </li>
  {% endfor %}
</ol>
<br/>
<a href="{% url 'post:create' %}"> <button>Create new post</button></a>
<br />
{% endblock %}

post/templates/update.html
{% extends 'base.html' %}
{% block head %}
  this is the update page
{% endblock %}

{% block body %}
<form action="{% url 'post:update' form.instance.id %}" method="POST">
  {% csrf_token %}
  {% for field in form %}
    {{ field.errors }}
    {{ field.label }} {{ field }} <br/>
  {% endfor %}
  <input type="submit" value="Update">
</form>
{% endblock %}